name:                http-queue
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saurabhnanda/http-queue#readme
license:             BSD3
author:              Saurabh Nanda
maintainer:          saurabhnanda@gmail.com
copyright:           Saurabh Nanda
category:            Web
extra-source-files:
- README.md

default-extensions:
- OverloadedStrings
- RecordWildCards
- DeriveGeneric
- FlexibleInstances
- FlexibleContexts
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- KindSignatures
- MultiParamTypeClasses
- TemplateHaskell
- TypeFamilies
- TypeSynonymInstances
- QuasiQuotes
- ScopedTypeVariables
- LambdaCase
- NamedFieldPuns

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - text
  - bytestring
  - time
  - unliftio
  - unliftio-core
  - either
  - warp
  - wai
  - safe
  - odd-jobs
  - wai-extra
  - http-types
  - http-client
  - http-client-tls
  - optparse-applicative
  - postgresql-simple
  - unordered-containers
  - vector
  - resource-pool
  - case-insensitive
  - hashable
  - fast-logger
  - async
  
ghc-options: 
  - -Wall 
  - -fno-warn-orphans 
  - -fno-warn-unused-imports 
  - -fno-warn-dodgy-exports
  - -Werror=missing-fields
  - -Werror=incomplete-patterns
  - -threaded
  - -with-rtsopts=-N

executables:
  http-queue-source:
    source-dirs:
      - common
      - source
    main:             Source.hs
    ghc-options:
      - -main-is Source

  http-queue-sink:
    source-dirs:
      - common
      - sink
    main:             Sink.hs
    ghc-options:
      - -main-is Sink

  http-queue-migrations:
    source-dirs:
      - common
      - migrations
    main:             Migrations.hs
    ghc-options:
      - -main-is Migrations

  http-queue-ui:
    source-dirs:
      - common
      - ui
    main:             UI.hs
    ghc-options:
      - -main-is UI
    dependencies:
      - lucid

tests:
  http-queue-tests:
    main: Test
    source-dirs:
      - common
      - source
      - sink
      - migrations
      - test
    dependencies:
      - tasty
      - hedgehog
      - tasty-hedgehog
      - tasty-hunit
      - random
      - monad-control
      - containers
      - lifted-async
      - monad-control
      - port-utils

